-- Persist the alphanumeric item code (SKU) onto every product record.
-- ADDITIVE ONLY: new column + fills it (name/size/prices untouched, guarded by sku='').

ALTER TABLE products ADD COLUMN sku TEXT NOT NULL DEFAULT '';

UPDATE products SET sku='CON-ALU-250ML' WHERE name='Aluminium Container' AND size='250 ml' AND sku='';
UPDATE products SET sku='CON-ALU-450ML' WHERE name='Aluminium Container' AND size='450 ml' AND sku='';
UPDATE products SET sku='CON-ALU-750ML' WHERE name='Aluminium Container' AND size='750 ml' AND sku='';
UPDATE products SET sku='FOIL-9MTR' WHERE name='Aluminium Foil' AND size='9 mtr' AND sku='';
UPDATE products SET sku='BAG-BIOECO-10X14' WHERE name='Bio Ecowin Carry Bag' AND size='10x14' AND sku='';
UPDATE products SET sku='BAG-BIOECO-13X16' WHERE name='Bio Ecowin Carry Bag' AND size='13x16' AND sku='';
UPDATE products SET sku='BAG-BIOECO-16X20' WHERE name='Bio Ecowin Carry Bag' AND size='16x20' AND sku='';
UPDATE products SET sku='BAG-BIOECO-17X23' WHERE name='Bio Ecowin Carry Bag' AND size='17x23' AND sku='';
UPDATE products SET sku='BAG-BIOECO-20X26' WHERE name='Bio Ecowin Carry Bag' AND size='20x26' AND sku='';
UPDATE products SET sku='PAPR-BROWN-BIG' WHERE name='Brown Paper' AND size='Big' AND sku='';
UPDATE products SET sku='PAPR-BROWN-LRG' WHERE name='Brown Paper' AND size='Large' AND sku='';
UPDATE products SET sku='PAPR-BROWN-MED' WHERE name='Brown Paper' AND size='Medium' AND sku='';
UPDATE products SET sku='PAPR-BROWN-SML' WHERE name='Brown Paper' AND size='Small' AND sku='';
UPDATE products SET sku='PAPR-BUTTER' WHERE name='Butter Paper' AND size='' AND sku='';
UPDATE products SET sku='CAP' WHERE name='Cap' AND size='' AND sku='';
UPDATE products SET sku='FILM-CLING-100MTR' WHERE name='Cling Film' AND size='100 mtr' AND sku='';
UPDATE products SET sku='FILM-CLING-60MTR' WHERE name='Cling Film' AND size='60 mtr' AND sku='';
UPDATE products SET sku='FILM-CLINGN-60MTR' WHERE name='Cling Film Normal' AND size='60 mtr' AND sku='';
UPDATE products SET sku='HMC-ELITE-1KG' WHERE name='Elite HM Cover' AND size='1 kg' AND sku='';
UPDATE products SET sku='HMC-ELITE-2KG' WHERE name='Elite HM Cover' AND size='2 kg' AND sku='';
UPDATE products SET sku='HMC-ELITE-250G' WHERE name='Elite HM Cover' AND size='250 gm' AND sku='';
UPDATE products SET sku='HMC-ELITE-3KG' WHERE name='Elite HM Cover' AND size='3 kg' AND sku='';
UPDATE products SET sku='HMC-ELITE-5KG' WHERE name='Elite HM Cover' AND size='5 kg' AND sku='';
UPDATE products SET sku='HMC-ELITE-500G' WHERE name='Elite HM Cover' AND size='500 gm' AND sku='';
UPDATE products SET sku='LDC-FINE-000' WHERE name='Fine Pack LD Cover' AND size='Triple Zero' AND sku='';
UPDATE products SET sku='GBAG-30X50' WHERE name='Garbage Bag' AND size='30x50' AND sku='';
UPDATE products SET sku='GBAG-LRG' WHERE name='Garbage Bag' AND size='Large' AND sku='';
UPDATE products SET sku='GBAG-MED' WHERE name='Garbage Bag' AND size='Medium' AND sku='';
UPDATE products SET sku='GBAG-SML' WHERE name='Garbage Bag' AND size='Small' AND sku='';
UPDATE products SET sku='GLOV-NORMAL' WHERE name='Gloves Normal' AND size='' AND sku='';
UPDATE products SET sku='GLOV-SURG' WHERE name='Gloves Surgical' AND size='' AND sku='';
UPDATE products SET sku='LDC-GULF-10X12' WHERE name='Gulf LD Cover' AND size='10x12' AND sku='';
UPDATE products SET sku='LDC-GULF-10X14' WHERE name='Gulf LD Cover' AND size='10x14' AND sku='';
UPDATE products SET sku='LDC-GULF-12X18' WHERE name='Gulf LD Cover' AND size='12x18' AND sku='';
UPDATE products SET sku='CUP-ICE-50NOS' WHERE name='Ice Cup' AND size='50 nos' AND sku='';
UPDATE products SET sku='HMC-JM-1KG' WHERE name='JM HM Cover' AND size='1 kg' AND sku='';
UPDATE products SET sku='HMC-JM-2KG' WHERE name='JM HM Cover' AND size='2 kg' AND sku='';
UPDATE products SET sku='HMC-JM-250G' WHERE name='JM HM Cover' AND size='250 gm' AND sku='';
UPDATE products SET sku='HMC-JM-3KG' WHERE name='JM HM Cover' AND size='3 kg' AND sku='';
UPDATE products SET sku='HMC-JM-500G' WHERE name='JM HM Cover' AND size='500 gm' AND sku='';
UPDATE products SET sku='LEAF-JM-BIG' WHERE name='JM Leaf' AND size='Big' AND sku='';
UPDATE products SET sku='LEAF-JM-SML' WHERE name='JM Leaf' AND size='Small' AND sku='';
UPDATE products SET sku='GLS-JUICE-250ML' WHERE name='Juice Glass' AND size='250 ml' AND sku='';
UPDATE products SET sku='GLS-JUICE-300ML' WHERE name='Juice Glass' AND size='300 ml' AND sku='';
UPDATE products SET sku='GLS-JUICELID-300ML' WHERE name='Juice Glass with Lid' AND size='300 ml' AND sku='';
UPDATE products SET sku='BAG-KING-10X14' WHERE name='King Carry Bag' AND size='10x14' AND sku='';
UPDATE products SET sku='BAG-KING-13X16' WHERE name='King Carry Bag' AND size='13x16' AND sku='';
UPDATE products SET sku='BAG-KING-16X20' WHERE name='King Carry Bag' AND size='16x20' AND sku='';
UPDATE products SET sku='MASK' WHERE name='Mask' AND size='' AND sku='';
UPDATE products SET sku='CUP-MAYO-100ML' WHERE name='Mayonnaise Cup' AND size='100 ml' AND sku='';
UPDATE products SET sku='CUP-MAYO-35ML' WHERE name='Mayonnaise Cup' AND size='35 ml' AND sku='';
UPDATE products SET sku='CUP-MAYO-50ML' WHERE name='Mayonnaise Cup' AND size='50 ml' AND sku='';
UPDATE products SET sku='LDC-GOLD-1KG' WHERE name='Money Gold LD Cover' AND size='1 kg' AND sku='';
UPDATE products SET sku='LDC-GOLD-10KG' WHERE name='Money Gold LD Cover' AND size='10 kg' AND sku='';
UPDATE products SET sku='LDC-GOLD-2KG' WHERE name='Money Gold LD Cover' AND size='2 kg' AND sku='';
UPDATE products SET sku='LDC-GOLD-250G' WHERE name='Money Gold LD Cover' AND size='250 gm' AND sku='';
UPDATE products SET sku='LDC-GOLD-3KG' WHERE name='Money Gold LD Cover' AND size='3 kg' AND sku='';
UPDATE products SET sku='LDC-GOLD-5KG' WHERE name='Money Gold LD Cover' AND size='5 kg' AND sku='';
UPDATE products SET sku='LDC-GOLD-500G' WHERE name='Money Gold LD Cover' AND size='500 gm' AND sku='';
UPDATE products SET sku='ROLL-NECK' WHERE name='Neck Roll' AND size='' AND sku='';
UPDATE products SET sku='NWC-10X14' WHERE name='Non Woven Cover' AND size='10x14' AND sku='';
UPDATE products SET sku='NWC-13X16' WHERE name='Non Woven Cover' AND size='13x16' AND sku='';
UPDATE products SET sku='NWC-16X20' WHERE name='Non Woven Cover' AND size='16x20' AND sku='';
UPDATE products SET sku='NET-ONION' WHERE name='Onion Net' AND size='' AND sku='';
UPDATE products SET sku='BAG-PALM-10X14' WHERE name='Palmtree Carry Bag' AND size='10x14' AND sku='';
UPDATE products SET sku='BAG-PALM-13X16' WHERE name='Palmtree Carry Bag' AND size='13x16' AND sku='';
UPDATE products SET sku='BAG-PALM-16X20' WHERE name='Palmtree Carry Bag' AND size='16x20' AND sku='';
UPDATE products SET sku='BAG-PALM-17X23' WHERE name='Palmtree Carry Bag' AND size='17x23' AND sku='';
UPDATE products SET sku='BAG-PALM-20X26' WHERE name='Palmtree Carry Bag' AND size='20x26' AND sku='';
UPDATE products SET sku='GLS-PAPBIO-150ML' WHERE name='Paper Glass Bio' AND size='150 ml' AND sku='';
UPDATE products SET sku='GLS-PAPBIO-200ML' WHERE name='Paper Glass Bio' AND size='200 ml' AND sku='';
UPDATE products SET sku='GLS-PAPER-150ML' WHERE name='Paper Glass Normal' AND size='150 ml' AND sku='';
UPDATE products SET sku='GLS-PAPER-200ML' WHERE name='Paper Glass Normal' AND size='200 ml' AND sku='';
UPDATE products SET sku='CON-PRECT-750ML' WHERE name='Plastic Container Rectangle' AND size='750 ml' AND sku='';
UPDATE products SET sku='CON-PRND-250ML' WHERE name='Plastic Container Round' AND size='250 ml' AND sku='';
UPDATE products SET sku='CON-PRND-500ML' WHERE name='Plastic Container Round' AND size='500 ml' AND sku='';
UPDATE products SET sku='CON-PRND-750ML' WHERE name='Plastic Container Round' AND size='750 ml' AND sku='';
UPDATE products SET sku='GLS-PLAS-250ML' WHERE name='Plastic Glass' AND size='250 ml' AND sku='';
UPDATE products SET sku='GLS-PLASHARD-250ML' WHERE name='Plastic Glass Hard' AND size='250 ml' AND sku='';
UPDATE products SET sku='PLT-10X10' WHERE name='Plate' AND size='10x10' AND sku='';
UPDATE products SET sku='PLT-10X12' WHERE name='Plate' AND size='10x12' AND sku='';
UPDATE products SET sku='PLT-6IN' WHERE name='Plate' AND size='6 inch' AND sku='';
UPDATE products SET sku='PLT-8IN' WHERE name='Plate' AND size='8 inch' AND sku='';
UPDATE products SET sku='BAG-POWER-17X23' WHERE name='Power Carry Bag' AND size='17x23' AND sku='';
UPDATE products SET sku='BAG-POWER-20X26' WHERE name='Power Carry Bag' AND size='20x26' AND sku='';
UPDATE products SET sku='BAG-POWER-24X30' WHERE name='Power Carry Bag' AND size='24x30' AND sku='';
UPDATE products SET sku='BAG-POWER-27X30' WHERE name='Power Carry Bag' AND size='27x30' AND sku='';
UPDATE products SET sku='PPC-DT-10X12' WHERE name='PP Cover Double T' AND size='10x12' AND sku='';
UPDATE products SET sku='PPC-DT-10X14' WHERE name='PP Cover Double T' AND size='10x14' AND sku='';
UPDATE products SET sku='PPC-DT-4X5' WHERE name='PP Cover Double T' AND size='4x5' AND sku='';
UPDATE products SET sku='PPC-DT-5X6' WHERE name='PP Cover Double T' AND size='5x6' AND sku='';
UPDATE products SET sku='PPC-DT-5X7' WHERE name='PP Cover Double T' AND size='5x7' AND sku='';
UPDATE products SET sku='PPC-DT-5X8' WHERE name='PP Cover Double T' AND size='5x8' AND sku='';
UPDATE products SET sku='PPC-DT-5X9' WHERE name='PP Cover Double T' AND size='5x9' AND sku='';
UPDATE products SET sku='PPC-DT-6X7' WHERE name='PP Cover Double T' AND size='6x7' AND sku='';
UPDATE products SET sku='PPC-DT-6X8' WHERE name='PP Cover Double T' AND size='6x8' AND sku='';
UPDATE products SET sku='PPC-DT-6X9' WHERE name='PP Cover Double T' AND size='6x9' AND sku='';
UPDATE products SET sku='PPC-DT-7X9' WHERE name='PP Cover Double T' AND size='7x9' AND sku='';
UPDATE products SET sku='PPC-DT-8X10' WHERE name='PP Cover Double T' AND size='8x10' AND sku='';
UPDATE products SET sku='PPC-DT-9X11' WHERE name='PP Cover Double T' AND size='9x11' AND sku='';
UPDATE products SET sku='PPC-NICE-10X11' WHERE name='PP Cover Nice' AND size='10x11' AND sku='';
UPDATE products SET sku='PPC-NICE-4X6' WHERE name='PP Cover Nice' AND size='4x6' AND sku='';
UPDATE products SET sku='PPC-NICE-5X6' WHERE name='PP Cover Nice' AND size='5x6' AND sku='';
UPDATE products SET sku='PPC-NICE-5X7' WHERE name='PP Cover Nice' AND size='5x7' AND sku='';
UPDATE products SET sku='PPC-NICE-6X7' WHERE name='PP Cover Nice' AND size='6x7' AND sku='';
UPDATE products SET sku='PPC-NICE-7X9' WHERE name='PP Cover Nice' AND size='7x9' AND sku='';
UPDATE products SET sku='PPC-NICE-8X10' WHERE name='PP Cover Nice' AND size='8x10' AND sku='';
UPDATE products SET sku='PPC-NICE-9X11' WHERE name='PP Cover Nice' AND size='9x11' AND sku='';
UPDATE products SET sku='PPC-ST-10X12' WHERE name='PP Cover Single T' AND size='10x12' AND sku='';
UPDATE products SET sku='PPC-ST-10X14' WHERE name='PP Cover Single T' AND size='10x14' AND sku='';
UPDATE products SET sku='PPC-ST-4X5' WHERE name='PP Cover Single T' AND size='4x5' AND sku='';
UPDATE products SET sku='PPC-ST-5X6' WHERE name='PP Cover Single T' AND size='5x6' AND sku='';
UPDATE products SET sku='PPC-ST-5X7' WHERE name='PP Cover Single T' AND size='5x7' AND sku='';
UPDATE products SET sku='PPC-ST-5X8' WHERE name='PP Cover Single T' AND size='5x8' AND sku='';
UPDATE products SET sku='PPC-ST-5X9' WHERE name='PP Cover Single T' AND size='5x9' AND sku='';
UPDATE products SET sku='PPC-ST-6X7' WHERE name='PP Cover Single T' AND size='6x7' AND sku='';
UPDATE products SET sku='PPC-ST-6X8' WHERE name='PP Cover Single T' AND size='6x8' AND sku='';
UPDATE products SET sku='PPC-ST-6X9' WHERE name='PP Cover Single T' AND size='6x9' AND sku='';
UPDATE products SET sku='PPC-ST-7X9' WHERE name='PP Cover Single T' AND size='7x9' AND sku='';
UPDATE products SET sku='PPC-ST-8X10' WHERE name='PP Cover Single T' AND size='8x10' AND sku='';
UPDATE products SET sku='PPC-ST-9X11' WHERE name='PP Cover Single T' AND size='9x11' AND sku='';
UPDATE products SET sku='ROLL-NORMAL' WHERE name='Roll Normal' AND size='' AND sku='';
UPDATE products SET sku='RBAND-HALFKG' WHERE name='Rubber Band' AND size='1/2 kg' AND sku='';
UPDATE products SET sku='ROLL-SAREE' WHERE name='Saree Roll' AND size='' AND sku='';
UPDATE products SET sku='LEAF-SASBIO-BIG' WHERE name='SAS Bio Leaf' AND size='Big' AND sku='';
UPDATE products SET sku='LEAF-SASBIO-SML' WHERE name='SAS Bio Leaf' AND size='Small' AND sku='';
UPDATE products SET sku='LEAF-SAS-BIG' WHERE name='SAS Normal Leaf' AND size='Big' AND sku='';
UPDATE products SET sku='LEAF-SAS-SML' WHERE name='SAS Normal Leaf' AND size='Small' AND sku='';
UPDATE products SET sku='ROLL-SHAW-1KG' WHERE name='Shawarma Roll' AND size='1 kg' AND sku='';
UPDATE products SET sku='SHT-NICE-12X12' WHERE name='Sheet Nice' AND size='12x12' AND sku='';
UPDATE products SET sku='SHT-NICE-18X18' WHERE name='Sheet Nice' AND size='18x18' AND sku='';
UPDATE products SET sku='SHT-NORMAL-12X12' WHERE name='Sheet Normal' AND size='12x12' AND sku='';
UPDATE products SET sku='SHT-NORMAL-15X15' WHERE name='Sheet Normal' AND size='15x15' AND sku='';
UPDATE products SET sku='SHT-NORMAL-18X18' WHERE name='Sheet Normal' AND size='18x18' AND sku='';
UPDATE products SET sku='POUCH-SILVER-10X12' WHERE name='Silver Pouch' AND size='10x12' AND sku='';
UPDATE products SET sku='POUCH-SILVER-10X14' WHERE name='Silver Pouch' AND size='10x14' AND sku='';
UPDATE products SET sku='POUCH-SILVER-4X6' WHERE name='Silver Pouch' AND size='4x6' AND sku='';
UPDATE products SET sku='POUCH-SILVER-5X7' WHERE name='Silver Pouch' AND size='5x7' AND sku='';
UPDATE products SET sku='POUCH-SILVER-6X8' WHERE name='Silver Pouch' AND size='6x8' AND sku='';
UPDATE products SET sku='POUCH-SILVER-7X9' WHERE name='Silver Pouch' AND size='7x9' AND sku='';
UPDATE products SET sku='POUCH-SILVER-8X10' WHERE name='Silver Pouch' AND size='8x10' AND sku='';
UPDATE products SET sku='HMC-SOFTY-1KG' WHERE name='Softy HM Cover' AND size='1 kg' AND sku='';
UPDATE products SET sku='HMC-SOFTY-10KG' WHERE name='Softy HM Cover' AND size='10 kg' AND sku='';
UPDATE products SET sku='HMC-SOFTY-2KG' WHERE name='Softy HM Cover' AND size='2 kg' AND sku='';
UPDATE products SET sku='HMC-SOFTY-250G' WHERE name='Softy HM Cover' AND size='250 gm' AND sku='';
UPDATE products SET sku='HMC-SOFTY-3KG' WHERE name='Softy HM Cover' AND size='3 kg' AND sku='';
UPDATE products SET sku='HMC-SOFTY-5KG' WHERE name='Softy HM Cover' AND size='5 kg' AND sku='';
UPDATE products SET sku='HMC-SOFTY-500G' WHERE name='Softy HM Cover' AND size='500 gm' AND sku='';
UPDATE products SET sku='LDC-SPICE-1KG' WHERE name='Spice LD Cover' AND size='1 kg' AND sku='';
UPDATE products SET sku='LDC-SPICE-10KG' WHERE name='Spice LD Cover' AND size='10 kg' AND sku='';
UPDATE products SET sku='LDC-SPICE-15KG' WHERE name='Spice LD Cover' AND size='15 kg' AND sku='';
UPDATE products SET sku='LDC-SPICE-2KG' WHERE name='Spice LD Cover' AND size='2 kg' AND sku='';
UPDATE products SET sku='LDC-SPICE-20KG' WHERE name='Spice LD Cover' AND size='20 kg' AND sku='';
UPDATE products SET sku='LDC-SPICE-25KG' WHERE name='Spice LD Cover' AND size='25 kg' AND sku='';
UPDATE products SET sku='LDC-SPICE-250G' WHERE name='Spice LD Cover' AND size='250 gm' AND sku='';
UPDATE products SET sku='LDC-SPICE-3KG' WHERE name='Spice LD Cover' AND size='3 kg' AND sku='';
UPDATE products SET sku='LDC-SPICE-5KG' WHERE name='Spice LD Cover' AND size='5 kg' AND sku='';
UPDATE products SET sku='LDC-SPICE-500G' WHERE name='Spice LD Cover' AND size='500 gm' AND sku='';
UPDATE products SET sku='SPOON' WHERE name='Spoon' AND size='' AND sku='';
UPDATE products SET sku='POUCH-STAND-200ML' WHERE name='Standing Pouch' AND size='200 ml' AND sku='';
UPDATE products SET sku='POUCH-STAND-500ML' WHERE name='Standing Pouch' AND size='500 ml' AND sku='';
UPDATE products SET sku='STRAW-BIG' WHERE name='Straw' AND size='Big' AND sku='';
UPDATE products SET sku='STRAW-SML' WHERE name='Straw' AND size='Small' AND sku='';
UPDATE products SET sku='FILM-STRETCH-BIG' WHERE name='Stretch Film' AND size='Big' AND sku='';
UPDATE products SET sku='FILM-STRETCH-SML' WHERE name='Stretch Film' AND size='Small' AND sku='';
UPDATE products SET sku='BAG-SDMND-10X14' WHERE name='Superdiamond Carry Bag' AND size='10x14' AND sku='';
UPDATE products SET sku='BAG-SDMND-13X16' WHERE name='Superdiamond Carry Bag' AND size='13x16' AND sku='';
UPDATE products SET sku='BAG-SDMND-16X20' WHERE name='Superdiamond Carry Bag' AND size='16x20' AND sku='';
UPDATE products SET sku='TIS-BOX' WHERE name='Tissue Box' AND size='' AND sku='';
UPDATE products SET sku='TIS-KITCHEN' WHERE name='Tissue Kitchen' AND size='' AND sku='';
UPDATE products SET sku='TIS-POLO' WHERE name='Tissue Polo' AND size='' AND sku='';
UPDATE products SET sku='TIS-PRIME' WHERE name='Tissue Prime' AND size='' AND sku='';
UPDATE products SET sku='TIS-RISSUN' WHERE name='Tissue Rissun' AND size='' AND sku='';
UPDATE products SET sku='PLT-VIP-10X12' WHERE name='VIP Plate' AND size='10x12' AND sku='';
UPDATE products SET sku='BAG-WCUP-10X14' WHERE name='World Cup Carry Bag' AND size='10x14' AND sku='';
UPDATE products SET sku='BAG-WCUP-13X16' WHERE name='World Cup Carry Bag' AND size='13x16' AND sku='';
UPDATE products SET sku='BAG-WCUP-16X20' WHERE name='World Cup Carry Bag' AND size='16x20' AND sku='';
UPDATE products SET sku='BAG-WCUP-17X23' WHERE name='World Cup Carry Bag' AND size='17x23' AND sku='';
UPDATE products SET sku='HMC-ZAM-1KG' WHERE name='Zamkudi HM Cover' AND size='1 kg' AND sku='';
UPDATE products SET sku='HMC-ZAM-10KG' WHERE name='Zamkudi HM Cover' AND size='10 kg' AND sku='';
UPDATE products SET sku='HMC-ZAM-2KG' WHERE name='Zamkudi HM Cover' AND size='2 kg' AND sku='';
UPDATE products SET sku='HMC-ZAM-3KG' WHERE name='Zamkudi HM Cover' AND size='3 kg' AND sku='';
UPDATE products SET sku='HMC-ZAM-5KG' WHERE name='Zamkudi HM Cover' AND size='5 kg' AND sku='';
