-- Opening stock count (from the owner's handwritten stock take, 2026-07-20).
-- ADDITIVE ONLY: inserts stock_counts baseline rows keyed on name+size; a
-- missing item simply inserts nothing. Balances recompute from sales/purchases.

INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='JM Leaf' AND size='Small';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='JM Leaf' AND size='Big';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='SAS Normal Leaf' AND size='Small';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='SAS Normal Leaf' AND size='Big';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='SAS Bio Leaf' AND size='Small';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='SAS Bio Leaf' AND size='Big';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Gulf LD Cover' AND size='10x14';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='Gulf LD Cover' AND size='12x18';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='PP Cover Double T' AND size='8x10';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='PP Cover Single T' AND size='8x10';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='PP Cover Nice' AND size='7x9';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='PP Cover Single T' AND size='7x9';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='PP Cover Single T' AND size='6x8';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='PP Cover Nice' AND size='5x7';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='PP Cover Double T' AND size='5x7';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='PP Cover Nice' AND size='5x6';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 6, '2026-07-20' FROM products WHERE name='Paper Glass Normal' AND size='150 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 15, '2026-07-20' FROM products WHERE name='Paper Glass Bio' AND size='150 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Paper Glass Normal' AND size='200 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Paper Glass Bio' AND size='200 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='Juice Glass with Lid' AND size='300 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='Plastic Glass' AND size='250 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Plastic Glass Hard' AND size='250 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='Money Gold LD Cover' AND size='250 gm';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 6, '2026-07-20' FROM products WHERE name='Money Gold LD Cover' AND size='500 gm';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='Money Gold LD Cover' AND size='1 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 6, '2026-07-20' FROM products WHERE name='Money Gold LD Cover' AND size='2 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Money Gold LD Cover' AND size='3 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Money Gold LD Cover' AND size='5 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='Money Gold LD Cover' AND size='10 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 12, '2026-07-20' FROM products WHERE name='Ice Cup' AND size='50 nos';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 30, '2026-07-20' FROM products WHERE name='Fine Pack LD Cover' AND size='Triple Zero';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='Mask' AND size='';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 18, '2026-07-20' FROM products WHERE name='Tissue Rissun' AND size='';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Mayonnaise Cup' AND size='35 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='Mayonnaise Cup' AND size='50 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 14, '2026-07-20' FROM products WHERE name='Tissue Polo' AND size='';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 7, '2026-07-20' FROM products WHERE name='Straw' AND size='Big';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 13, '2026-07-20' FROM products WHERE name='Straw' AND size='Small';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Silver Pouch' AND size='10x14';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='Silver Pouch' AND size='10x12';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 6, '2026-07-20' FROM products WHERE name='Silver Pouch' AND size='8x10';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Silver Pouch' AND size='7x9';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 7, '2026-07-20' FROM products WHERE name='Silver Pouch' AND size='6x8';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Silver Pouch' AND size='5x7';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Silver Pouch' AND size='4x6';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Aluminium Container' AND size='250 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Aluminium Container' AND size='450 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Aluminium Container' AND size='750 ml';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Cling Film' AND size='100 mtr';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='Aluminium Foil' AND size='9 mtr';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='Brown Paper' AND size='Big';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Brown Paper' AND size='Medium';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='Brown Paper' AND size='Small';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 8, '2026-07-20' FROM products WHERE name='Gloves Normal' AND size='';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 8, '2026-07-20' FROM products WHERE name='Garbage Bag' AND size='30x50';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='Garbage Bag' AND size='Small';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Plate' AND size='6 inch';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='Plate' AND size='8 inch';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 7, '2026-07-20' FROM products WHERE name='VIP Plate' AND size='10x12';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Roll Normal' AND size='';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 1, '2026-07-20' FROM products WHERE name='Bio Ecowin Carry Bag' AND size='20x26';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Palmtree Carry Bag' AND size='17x23';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 15, '2026-07-20' FROM products WHERE name='Palmtree Carry Bag' AND size='10x14';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 20, '2026-07-20' FROM products WHERE name='Palmtree Carry Bag' AND size='13x16';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 18, '2026-07-20' FROM products WHERE name='Palmtree Carry Bag' AND size='16x20';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 7, '2026-07-20' FROM products WHERE name='World Cup Carry Bag' AND size='10x14';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='World Cup Carry Bag' AND size='13x16';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 6, '2026-07-20' FROM products WHERE name='World Cup Carry Bag' AND size='16x20';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Superdiamond Carry Bag' AND size='10x14';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='Superdiamond Carry Bag' AND size='13x16';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Superdiamond Carry Bag' AND size='16x20';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='Elite HM Cover' AND size='250 gm';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='Elite HM Cover' AND size='500 gm';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Elite HM Cover' AND size='2 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Elite HM Cover' AND size='3 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='Softy HM Cover' AND size='250 gm';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Softy HM Cover' AND size='500 gm';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 2, '2026-07-20' FROM products WHERE name='Softy HM Cover' AND size='1 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Zamkudi HM Cover' AND size='1 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Zamkudi HM Cover' AND size='2 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Zamkudi HM Cover' AND size='3 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Zamkudi HM Cover' AND size='5 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='Zamkudi HM Cover' AND size='10 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Spice LD Cover' AND size='10 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Spice LD Cover' AND size='5 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Spice LD Cover' AND size='3 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Spice LD Cover' AND size='2 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Spice LD Cover' AND size='1 kg';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 9, '2026-07-20' FROM products WHERE name='Spice LD Cover' AND size='500 gm';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 10, '2026-07-20' FROM products WHERE name='Spice LD Cover' AND size='250 gm';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 3, '2026-07-20' FROM products WHERE name='Sheet Normal' AND size='12x12';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Sheet Nice' AND size='12x12';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 4, '2026-07-20' FROM products WHERE name='Sheet Normal' AND size='18x18';
INSERT INTO stock_counts (product_id, qty, count_date) SELECT id, 5, '2026-07-20' FROM products WHERE name='Sheet Nice' AND size='18x18';
